---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.1.3
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Designing and Creating a DB

This is the guided proyect for the Intermediate SQL section of DataQuest. 


## Importing and Analysing Data in Pandas

```{python}
# Importing libraries
import pandas as pd
import numpy as np
import sqlite3
import csv
```

```{python}
# Additional pandas configuration for working with big datasets
pd.set_option('max_columns', 180)
pd.set_option('max_rows', 200000)
pd.set_option('max_colwidth', 5000)
```

```{python}
# !ls data
```

```{python}
# Rading the four files in which the information is contained

game_log = pd.read_csv('./data/game_log.csv', low_memory = False)
park_codes = pd.read_csv('./data/park_codes.csv')
person_codes = pd.read_csv('./data/person_codes.csv')
team_codes = pd.read_csv('./data/team_codes.csv')

```

```{python}
# Inspecting game_log
# There are 172 000 games
# Each game have the date, number of games, players, teams and locations. 
# Scores, umpires, awards and attendance are also included

print('shape: ', game_log.shape)
game_log.head()
```

```{python}
# Games range from 1871 to 2016
game_log['date'].value_counts().sort_index()
```

```{python}
# Inspecting parK_codes
# The matching attribute with game_log could be park_id
# There are 252 stadiums, each with a unique park_id key
print('shape: ', park_codes.shape)
park_codes.head()
```

```{python}
# Inspecting person code
# The connection with game_log are the several attributes that contains a player id
# There are 20494 players registered, each with the debut as player, manager, coach or umpire. 
print('shape: ', person_codes.shape)
person_codes.head()
```

```{python}
# Inspecting team code
# The connection with game_log is the team_id attribute
# There are 150 registered teams with the nickname, range of activity and city they belong to.
print('shape: ', team_codes.shape)
team_codes.head()
```

```{python}
# Inspecting the franch_id attribute (team_codes)

print(team_codes['franch_id'].value_counts().head())

# Some teams have several franch_id

print('-'*5)

only_bs1 = team_codes['franch_id'] == 'BS1'

# The braves have always the same nickname and the same franch_id
# They have different id's, changing the location
# The sequence also shows the pathway of 'evolution'
print(team_codes[only_bs1])

print('-'*5)

# Still, nicknames and franch_id have not the same number of values (not a 1 to 1 correspondence)
# This indicates tht they might be teams with the same name but different location and franchise
print(team_codes['franch_id'].unique().shape[0])
print(team_codes['nickname'].unique().shape[0])
```

```{python}
# To analyze the 'def pos' of the series, unique values are inspected
game_log['v_player_1_def_pos'].value_counts().sort_index()
game_log['v_player_4_def_pos'].value_counts().sort_index()

# The values goes from one to 10. Each position from 1 to 9 correspond to a position in the field
# 1.Pitcher
# 2.Catcher
# 3.1st Base
# 4.2nd Base
# 5.3rd Base
# 6.Shortstop
# 7.Left Field
# 8.Center Field
# 9.Right Field

# The 10th value is not defined
```

## Saving the dataframes to a db with pandas and sqlite3

```{python}
# Creating helper functions to interact with the sqlite3 library

db = 'mlb.db'

def run_query(q):
    with sqlite3.connect(db) as conn:
        return pd.read_sql(q, conn)

def run_command(c):
    with sqlite3.connect(db) as conn:
        conn.isolation_level = None
        conn.execute(c)
        
def show_tables():
    q = '''
    select name, type
    from sqlite_master
    where type = "table"  or type = "view";
    '''
    
    return run_query(q)
```

```{python}
# Creating a table for each current data frame

tables = {
    'game_log': game_log,
    'person_codes': person_codes,
    'team_codes': team_codes,
    'park_codes': park_codes
}

# Add a try except conditional to avoid creating the tables when they already exist

try:
    run_query('''
    select * from game_log limit 5
    ''')
except:
    with sqlite3.connect(db) as conn:
        # Deconstruct each name in "name" and the data in "info"
        for name, info in tables.items():
            # Delete the table if it already exist on the db
            conn.execute('drop table if exists {}'.format(name))
            # Run the to_sql funciton on each dataset
            # The index = False ensures that the df index is not created as a new column on the sql table
            info.to_sql(name, conn, index = False)

show_tables()
```

```{python}
# Creating a new column on the game_log table to make the id

try:
    run_query('''
        select game_id
        from game_log
        limit 5
    ''')
except:
    run_command('''
    ALTER TABLE game_log
    ADD COLUMN game_id text
    ''')
    
    # Update the values of game_id to match the patter hometeam, year, month, day and number of game

    run_command('''
    UPDATE game_log
    SET game_id = h_name || date || number_of_game
    WHERE game_id IS NULL;
    ''')

run_query('''
select * 
from game_log
limit 10
''')

```

<!-- #region -->
## P3 and P4


## Normalization Opportunities and Defining a new Schema

The current tables can be reorginized using normal forms.

- We can eliminate all the debut dates and instead use the game_log data to calculate this value.
- The same can be done with the start, end and sequence attributes of the team_codes table.
- The start and end years of the park_code table can also be reproducible with the data on the game_log table.
- In the game_log table, there are rows in wich the name and the id of the player appear. The name can be obtained with the id, so we can eliminates the names on the game_log table

In regard to the schema reorganization, we could create a new table for specifing the position the player had in an specific game and if he played like a normal player, a manager or a coach, and the defensive and ofensive position it had. This table would be connected to the team table and the person table (for more specific details on the name). 

The team table would be connected to the specific league the team is part of. 

The game table would only have specific details for the game itself, and contain a foreign key related to a table of the game that specificates any statistics for the game and to the park table to know more details about where the game was played.

<!-- #endregion -->

## Creating tables of the new Schema that don't have foreign keys

To create the tables of the new schema, it's necessary to **start with the tables that don't have foreign keys**


```{python}
# Creating the new person, park and league tables

# Notice the use of "if not exist" for avoiding creating a new table when it already exists

run_command('''
    create table if not exists person(  
    person_id text primary key,
    first_name text,
    last_name text
    )
''')

run_command('''
    create table if not exists park(
        park_id text primary key,
        name text,
        nickname text,
        city text,
        state text,
        notes text
    )
''')

run_command('''
    create table if not exists league(
        league_id text primary key,
        league_name text
    )
''')


show_tables()
```

```{python}
# Inserting the values into the person, park an league tables

# Notice the use of "insert or ignore" to prevent adding again the same rows

run_command('''
    insert or ignore into person
    select id, first, last from person_codes;
''')

run_command('''
    insert or ignore into park
    select park_id, name, aka, city, state, notes from park_codes;
''')
    
run_command('''
    insert or ignore into league
    values
        ("NL", "National League"),
        ("AL", "American League"),
        ("AA", "American Association"),
        ("FL", "Federal League"),
        ("PL", "Players League"),
        ("UA", "Union Association");
''')


print(run_query('''
    select *
    from person
    limit 5
'''))

print(run_query('''
    select *
    from park
    limit 5
'''))

print(run_query('''
    select *
    from league
    limit 5
'''))
```

```{python}
# Reading the appearance_type from a csv

# droping the table appereance_type if it already exists

run_command('''
    drop table if exists appearance_type;
''')

# load the data to a df

appearance_type = pd.read_csv('./data/appearance_type.csv')

# Create first the table to avoid creating it and them having to create an additional table 

run_command('''
create table appearance_type(
    appearance_type_id text primary key,
    name text,
    category text
)
''')

# Load the df to the db
# Notice the "if_exists = 'append'" 

with sqlite3.connect(db) as conn:
    appearance_type.to_sql('appearance_type',
                          conn,
                          index = False,
                          if_exists = 'append')

run_query('''
    select *
    from appearance_type
    limit 15
''')
```

## Creating tables with foreign references 

```{python}
# Redefining the run_command function to ensure foreign key constraints on sql

def run_command(c):
    with sqlite3.connect(db) as conn:
        conn.execute('PRAGMA foreign_keys = ON;')
        conn.isolation_level = None
        conn.execute(c)

```

```{python}
# Creating the tables for the team and game

run_command('''
create table if not exists team(
    team_id text primary key,
    league_id text,
    city text,
    nickname text,
    franch_id text,
    foreign key (league_id) references league(league_id)
)
''')

run_command('''
create table if not exists game(
    game_id text primary key,
    date text,
    number_of_game integer,
    park_id text,
    length_outs integer,
    day integer,
    completion text,
    forfeit text,
    protest text,
    attendance integer,
    length_minutes integer,
    additional_info text,
    acquisition_info text,
    foreign key (park_id) references park(park_id)
)
''')


show_tables()
```

```{python}
run_query('''
select * from game_log limit 5
''')
```

```{python}
# Inserting values into team and game

run_command('''
    insert or ignore into team
    select team_id, league, city, nickname, franch_id from team_codes;
''')

run_command('''
    insert or ignore into game
    select 
        game_id,
        date,
        number_of_game,
        park_id,
        length_outs,
        case
            when day_night = "D" then 1
            when day_night = "N" then 0
            else null
            end as day,
        completion,
        forefeit,
        protest,
        attendance,
        length_minutes,
        additional_info,
        acquisition_info
        from game_log
''')

```

```{python}
# Checking the insertion of values

print(run_query('''
    select *
    from team
    limit 5
'''))


print(run_query('''
    select * from game limit 5
'''))

```

```{python}
# Creating the team appearence team

run_command('''
    create table if not exists team_appearance(
        team_id TEXT,
        game_id TEXT,
        home BOOLEAN,
        league_id TEXT,
        score INTEGER,
        line_score TEXT,
        at_bats INTEGER,
        hits INTEGER,
        doubles INTEGER,
        triples INTEGER,
        homeruns INTEGER,
        rbi INTEGER,
        sacrifice_hits INTEGER,
        sacrifice_flies INTEGER,
        hit_by_pitch INTEGER,
        walks INTEGER,
        intentional_walks INTEGER,
        strikeouts INTEGER,
        stolen_bases INTEGER,
        caught_stealing INTEGER,
        grounded_into_double INTEGER,
        first_catcher_interference INTEGER,
        left_on_base INTEGER,
        pitchers_used INTEGER,
        individual_earned_runs INTEGER,
        team_earned_runs INTEGER,
        wild_pitches INTEGER,
        balks INTEGER,
        putouts INTEGER,
        assists INTEGER,
        errors INTEGER,
        passed_balls INTEGER,
        double_plays INTEGER,
        triple_plays INTEGER,
        PRIMARY KEY (team_id, game_id),
        FOREIGN KEY (team_id) REFERENCES team(team_id),
        FOREIGN KEY (game_id) REFERENCES game(game_id),
        FOREIGN KEY (league_id) REFERENCES league(league_id)
    )
''')


print(show_tables())

# Inserting values into the team_appearance table
# Note how the table is split by selecting first only the rows of the home team and then the rows of the visitor team
# for each of the games and then joined using the "union" set operator.


run_command('''
insert or ignore into team_appearance
select 
    h_name,
    game_id,
    1 as home,
    h_league,
    h_score,
    h_line_score,
    h_at_bats,
    h_hits,
    h_doubles,
    h_triples,
    h_homeruns,
    h_rbi,
    h_sacrifice_hits,
    h_sacrifice_flies,
    h_hit_by_pitch,
    h_walks, 
    h_intentional_walks,
    h_strikeouts,
    h_stolen_bases,
    h_caught_stealing,
    h_grounded_into_double,
    h_first_catcher_interference,
    h_left_on_base,
    h_pitchers_used,
    h_individual_earned_runs,
    h_team_earned_runs,
    h_wild_pitches,
    h_balks,
    h_putouts,
    h_assists,
    h_errors,
    h_passed_balls,
    h_double_plays,
    h_triple_plays
from game_log

union

select 
    v_name,
    game_id,
    0 as home,
    v_league,
    v_score,
    v_line_score,
    v_at_bats,
    v_hits,
    v_doubles,
    v_triples,
    v_homeruns,
    v_rbi,
    v_sacrifice_hits,
    v_sacrifice_flies,
    v_hit_by_pitch,
    v_walks, 
    v_intentional_walks,
    v_strikeouts,
    v_stolen_bases,
    v_caught_stealing,
    v_grounded_into_double,
    v_first_catcher_interference,
    v_left_on_base,
    v_pitchers_used,
    v_individual_earned_runs,
    v_team_earned_runs,
    v_wild_pitches,
    v_balks,
    v_putouts,
    v_assists,
    v_errors,
    v_passed_balls,
    v_double_plays,
    v_triple_plays
from game_log
''')


print(run_query('''
select * from team_appearance limit 50
'''))
```

```{python}
# Creating the person_appearance table

run_command('''
create table if not exists person_appearance(
    appearance_id integer primary key,
    person_id text,
    team_id text,
    game_id text,
    appearance_type_id text,
    foreign key (person_id) references person(person_id),
    foreign key (team_id) references team(team_id),
    foreign key (game_id) references game(game_id),
    foreign key (appearance_type_id) references appearance_type(appearance_type_id)
)

''')

print(show_tables())
```

```{python}
# Inserting values into the person_appearance table

# First insert every value that is not a player itself (i.e umpires, managers, awards and pitchers)
# Notice that in this case, there are arguments being passed to the insert clause.
# This is because we are not passing all the data points of the row (the first one, the key,
# is not being passed so SQL generate it automatically)


run_command('''
INSERT OR IGNORE INTO person_appearance (
    game_id,
    team_id,
    person_id,
    appearance_type_id
)

/* Selecting only hp umpires rows */
SELECT
    game_id,
    NULL,
    hp_umpire_id,
    "UHP"
FROM game_log
WHERE hp_umpire_id IS NOT NULL    
    
    union

/* Selecting only first base umpires rows */
select game_id, NULL, [1b_umpire_id], "U1B"
from game_log
where [1b_umpire_id] not null

union

/* Selecting only second base umpires rows */
select game_id, NULL, [2b_umpire_id], "U2B"
from game_log
where [2b_umpire_id] not null

union

/* Selecting only third base umpires rows */
select game_id, NULL, [3b_umpire_id], "U3B"
from game_log
where [3b_umpire_id] not null

union

/* Selecting only left field umpires rows */
select game_id, NULL, lf_umpire_id, "ULF"
from game_log
where lf_umpire_id not null

union

/* Selecting only right field umpires rows */
select game_id, NULL, rf_umpire_id, "URF"
from game_log
where rf_umpire_id not null

union

/* Selecting only visitor managers rows */
select game_id, v_name, v_manager_id, "MM"
from game_log
where v_manager_id not null

union

/* Selecting only home managers rows */
select game_id, h_name, h_manager_id, "MM"
from game_log
where h_manager_id not null

union

/* Selecting only winning pitchers rows */
select 
    game_id,
    case 
        when h_score > v_score then h_name
        else v_name
        end as team_id,
    winning_pitcher_id, 
    "AWP"
from game_log
where winning_pitcher_id is not null

union

/* Selecting only losing pitchers rows */
select 
    game_id,
    case 
        when h_score > v_score then v_name
        else h_name
        end as team_id,
    losing_pitcher_id, 
    "ALP"
from game_log
where losing_pitcher_id is not null

union

/* Selecting only saving pitchers rows */
select 
    game_id,
    case 
        when h_score > v_score then h_name
        else v_name
        end as team_id,
    saving_pitcher_id, 
    "ASP"
from game_log
where saving_pitcher_id is not null

union

/* Selecting only winning rbi batters rows */
select 
    game_id,
    case 
        when h_score > v_score then h_name
        else v_name
        end as team_id,
    winning_rbi_batter_id, 
    "AWB"
from game_log
where winning_rbi_batter_id is not null


union

/* Selecting only visitor starting pitcher rows */
select 
    game_id,
    v_name,
    v_starting_pitcher_id, 
    "PSP"
from game_log
where v_starting_pitcher_id is not null

union

/* Selecting only home starting pitcher rows */
select 
    game_id,
    h_name,
    h_starting_pitcher_id, 
    "PSP"
from game_log
where h_starting_pitcher_id is not null;
''')




run_query('''
select *
from person_appearance
limit 15
''')
```

```{python}
# Inserting the values of each of the players

template = '''
insert or ignore into person_appearance(
    game_id,
    team_id,
    person_id,
    appearance_type_id
)

select 
    game_id,
    {homevisitor}_name,
    {homevisitor}_player_{number}_id,
    "O{number}"
from game_log
where {homevisitor}_player_{number}_id is not null

union

select 
    game_id,
    {homevisitor}_name,
    {homevisitor}_player_{number}_id,
    "D" || CAST({homevisitor}_player_{number}_def_pos as int)
from game_log
where {homevisitor}_player_{number}_id is not null
'''

for homevisitor in ['h', 'v']:
    for number in range(1,10):
        query_vars = {
            'homevisitor': homevisitor,
            'number': number
        }
        run_command(template.format(**query_vars))
        

```

```{python}
# Checking that both tables have the same number of game_id's
print(
run_query('''
select count(distinct game_id) from person_appearance
''')
)

print(
run_query('''
select count(game_id) from game
''')
)
```

## Droping initial tables

```{python}
# The four first initial tables that were used to insert values into the new schema
# can be deleted now

run_command('''
    drop table game_log
''')

run_command('''
    drop table person_codes
''')

run_command('''
    drop table team_codes
''')

run_command('''
    drop table park_codes
''')
```

```{python}
run_query('''
    select *
    from game
    limit 15
''')
```
